#!/usr/bin/env bash
# Install BEAM systemd units (orchestrator@, worker@, global-gateway).
#
# AWS EC2 (Ubuntu): run as ubuntu, use sudo for install:
#   ./scripts/setup-ec2.sh
#   sudo ./scripts/install-systemd.sh --enable
#   sudo ./scripts/install-systemd.sh --enable-global-gateway
#
# Usage:
#   ./scripts/install-systemd.sh --enable
#   ./scripts/install-systemd.sh --enable-orchestrators
#   ./scripts/install-systemd.sh --enable-workers
#   ./scripts/install-systemd.sh --enable-global-gateway
#   ./scripts/install-systemd.sh --enable-workers --instances worker1,worker2
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BEAM_ROOT="$ROOT"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/systemd.sh"

SYSTEMD_DIR="${ROOT}/deploy/systemd"
TARGET_DIR="/etc/systemd/system"
BEAM_USER=""
BEAM_GROUP=""
ENABLE=0
ENABLE_ORCHESTRATORS=0
ENABLE_WORKERS=0
ENABLE_GLOBAL_GATEWAY=0
ORCH_INSTANCES=""
WORKER_INSTANCES=""

usage() {
  cat <<EOF
Usage: $0 [--user NAME] [--group NAME] [--enable | --enable-orchestrators | --enable-workers | --enable-global-gateway]
         [--instances NAME[,NAME...]]

  --user                 User to run services as (default: ubuntu on EC2 when run via sudo/root)
  --group                Group to run services as (default: primary group of --user)
  --enable               Install unit templates only (no instances enabled)
  --enable-orchestrators Enable orchestrator instances from config/orchestrators/*.env
  --sync-orchestrators   Alias for --enable-orchestrators
  --enable-workers       Enable worker instances from config/workers/*.env
  --sync-workers         Alias for --enable-workers
  --enable-global-gateway Enable beam-global-gateway.service (config/global-gateway.env)
  --sync-global-gateway   Alias for --enable-global-gateway
  --instances            Comma-separated instance names (default: all *.env in target dir)

Each config/<service>/<name>.env file becomes a systemd instance with its own log:
  config/orchestrators/<name>.env -> beam-orchestrator@<name>.service -> logs/orchestrators/<name>.log
  config/workers/<name>.env        -> beam-worker@<name>.service         -> logs/workers/<name>.log
  config/global-gateway.env        -> beam-global-gateway.service

Installs unit files for:
  beam-orchestrator@.service
  beam-worker@.service
  beam-global-gateway.service
  beam-orchestrators.target (generated by --enable-orchestrators)
  beam-workers.target (generated by --enable-workers)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)
      BEAM_USER="$2"
      shift 2
      ;;
    --group)
      BEAM_GROUP="$2"
      shift 2
      ;;
    --enable)
      ENABLE=1
      shift
      ;;
    --enable-orchestrators|--sync-orchestrators)
      ENABLE_ORCHESTRATORS=1
      shift
      ;;
    --enable-workers|--sync-workers)
      ENABLE_WORKERS=1
      shift
      ;;
    --enable-global-gateway|--sync-global-gateway)
      ENABLE_GLOBAL_GATEWAY=1
      shift
      ;;
    --instances)
      if [[ "$ENABLE_ORCHESTRATORS" -eq 1 ]]; then
        ORCH_INSTANCES="$2"
      elif [[ "$ENABLE_WORKERS" -eq 1 ]]; then
        WORKER_INSTANCES="$2"
      else
        echo "--instances requires --enable-orchestrators or --enable-workers" >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

BEAM_USER="${BEAM_USER:-$(beam_default_service_user)}"
BEAM_GROUP="${BEAM_GROUP:-$(beam_default_service_group)}"

if [[ "$ENABLE" -eq 0 && "$ENABLE_ORCHESTRATORS" -eq 0 && "$ENABLE_WORKERS" -eq 0 && "$ENABLE_GLOBAL_GATEWAY" -eq 0 ]]; then
  ENABLE=1
fi

resolve_instances() {
  local explicit="$1"
  local config_subdir="$2"
  local -n _out="$3"
  local instances=()

  if [[ -n "$explicit" ]]; then
    IFS=',' read -r -a instances <<< "$explicit"
    for i in "${!instances[@]}"; do
      instances[$i]="${instances[$i]// /}"
    done
  else
    mapfile -t instances < <(beam_list_instances_from_dir "${ROOT}/config/${config_subdir}")
  fi

  if [[ "${#instances[@]}" -eq 0 ]]; then
    echo "No instances to enable. Add config/${config_subdir}/<name>.env first." >&2
    return 1
  fi

  for instance in "${instances[@]}"; do
    [[ -z "$instance" ]] && continue
    if [[ ! -f "${ROOT}/config/${config_subdir}/${instance}.env" ]]; then
      echo "Missing env file for instance ${instance}: ${ROOT}/config/${config_subdir}/${instance}.env" >&2
      exit 1
    fi
  done

  _out=("${instances[@]}")
}

enable_orchestrator_instances() {
  local instances=()
  resolve_instances "$ORCH_INSTANCES" "orchestrators" instances
  beam_validate_orchestrator_configs
  beam_sync_orchestrators
  beam_enable_service_instances "beam-orchestrator" "${instances[@]}"
  for instance in "${instances[@]}"; do
    [[ -z "$instance" ]] && continue
    echo "  enabled beam-orchestrator@${instance}.service -> config/orchestrators/${instance}.env"
  done
}

enable_worker_instances() {
  local instances=()
  resolve_instances "$WORKER_INSTANCES" "workers" instances
  beam_sync_workers
  beam_enable_service_instances "beam-worker" "${instances[@]}"
  for instance in "${instances[@]}"; do
    [[ -z "$instance" ]] && continue
    echo "  enabled beam-worker@${instance}.service -> config/workers/${instance}.env"
  done
}

enable_global_gateway() {
  local env_file="${ROOT}/config/global-gateway.env"
  if [[ ! -f "$env_file" ]]; then
    echo "Missing env file: ${env_file}" >&2
    echo "Copy config/global-gateway.env.example to config/global-gateway.env" >&2
    exit 1
  fi
  if ! beam_unit_installed "beam-global-gateway.service"; then
    echo "Global gateway unit not installed. Run: $0 --enable" >&2
    exit 1
  fi
  beam_systemctl enable "beam-global-gateway.service"
  echo "  enabled beam-global-gateway.service -> config/global-gateway.env"
}

if [[ ! -d "$SYSTEMD_DIR" ]]; then
  echo "Missing systemd templates: ${SYSTEMD_DIR}" >&2
  exit 1
fi

if ! VENV="$(beam_resolve_venv)"; then
  echo "Missing virtualenv: create ${ROOT}/venv or ${ROOT}/.venv and run pip install -e ." >&2
  exit 1
fi

beam_prepare_repo_permissions

echo "Service user: ${BEAM_USER} (group: ${BEAM_GROUP})"
if [[ "${EUID}" -eq 0 && "${BEAM_USER}" == "ubuntu" && -z "${SUDO_USER:-}" ]]; then
  echo "Note: detected root shell on EC2 — systemd units will run as ubuntu."
fi

render_unit() {
  local src="$1"
  local dest_name="$2"
  sed \
    -e "s|@BEAM_ROOT@|${ROOT}|g" \
    -e "s|@BEAM_VENV@|${VENV}|g" \
    -e "s|@BEAM_USER@|${BEAM_USER}|g" \
    -e "s|@BEAM_GROUP@|${BEAM_GROUP}|g" \
    "$src" | sudo tee "${TARGET_DIR}/${dest_name}" >/dev/null
}

echo "Installing systemd units to ${TARGET_DIR}"
render_unit "${SYSTEMD_DIR}/beam-orchestrator@.service" "beam-orchestrator@.service"
render_unit "${SYSTEMD_DIR}/beam-worker@.service" "beam-worker@.service"
render_unit "${SYSTEMD_DIR}/beam-global-gateway.service" "beam-global-gateway.service"

sudo systemctl daemon-reload
echo "Installed:"
echo "  beam-orchestrator@.service"
echo "  beam-worker@.service"
echo "  beam-global-gateway.service"

if [[ "$ENABLE" -eq 1 ]]; then
  echo
  echo "Unit templates installed. Enable instances after creating env files:"
  echo "  cp config/orchestrators/orch1.env.example config/orchestrators/orch1.env"
  echo "  ./scripts/install-systemd.sh --enable-orchestrators"
  echo "  ./scripts/run-orchestrator.sh orch1"
  echo
  echo "  cp config/workers/worker1.env.example config/workers/worker1.env"
  echo "  ./scripts/install-systemd.sh --enable-workers"
  echo "  ./scripts/run-workers.sh start"
  echo
  echo "  cp config/global-gateway.env.example config/global-gateway.env"
  echo "  ./scripts/install-systemd.sh --enable-global-gateway"
  echo "  ./scripts/run-global-gateway.sh start"
fi

if [[ "$ENABLE_ORCHESTRATORS" -eq 1 ]]; then
  if ! beam_unit_installed "beam-orchestrator@.service"; then
    echo "Orchestrator template not installed. Run: $0 --enable" >&2
    exit 1
  fi
  enable_orchestrator_instances
  echo "Enabled orchestrators. Start with:"
  echo "  ./scripts/run-orchestrators.sh start"
  echo "  ./scripts/run-orchestrator.sh <instance>"
fi

if [[ "$ENABLE_WORKERS" -eq 1 ]]; then
  if ! beam_unit_installed "beam-worker@.service"; then
    echo "Worker template not installed. Run: $0 --enable" >&2
    exit 1
  fi
  enable_worker_instances
  echo "Enabled workers. Start with:"
  echo "  ./scripts/run-workers.sh start"
  echo "  ./scripts/run-worker.sh <instance>"
fi

if [[ "$ENABLE_GLOBAL_GATEWAY" -eq 1 ]]; then
  if ! beam_unit_installed "beam-global-gateway.service"; then
    echo "Global gateway unit not installed. Run: $0 --enable" >&2
    exit 1
  fi
  enable_global_gateway
  echo "Enabled global gateway. Start with:"
  echo "  ./scripts/run-global-gateway.sh start"
  echo "  ./scripts/run-global-gateway.sh foreground"
fi
