#!/usr/bin/env bash
# Install BEAM systemd units (orchestrator, worker-gateway, worker@).
#
# Usage:
#   ./scripts/install-systemd.sh --enable
#   ./scripts/install-systemd.sh --enable-workers
#   ./scripts/install-systemd.sh --enable-workers --instances worker1,worker2
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BEAM_ROOT="$ROOT"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/systemd.sh"

SYSTEMD_DIR="${ROOT}/deploy/systemd"
TARGET_DIR="/etc/systemd/system"
BEAM_USER="${USER}"
BEAM_GROUP="${USER}"
ENABLE=0
ENABLE_WORKERS=0
INSTANCES=""

usage() {
  cat <<EOF
Usage: $0 [--user NAME] [--group NAME] [--enable | --enable-workers] [--instances worker1,worker2]

  --user            User to run services as (default: ${USER})
  --group           Group to run services as (default: same as --user)
  --enable          Install units and enable orchestrator + gateway only
  --enable-workers  Enable worker instances from config/workers/*.env
                    (run separately after worker env files are ready)
  --sync-workers    Alias for --enable-workers
  --instances       Comma-separated worker instances (default: all *.env)

Each config/workers/<name>.env file becomes beam-worker@<name>.service with its
own log at logs/workers/<name>.log.

Installs unit files for:
  beam-orchestrator.service
  beam-worker-gateway.service
  beam-worker@.service
  beam-workers.target (generated by --enable-workers)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)
      BEAM_USER="$2"
      shift 2
      ;;
    --group)
      BEAM_GROUP="$2"
      shift 2
      ;;
    --enable)
      ENABLE=1
      shift
      ;;
    --enable-workers|--sync-workers)
      ENABLE_WORKERS=1
      shift
      ;;
    --instances)
      INSTANCES="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

enable_worker_instances() {
  local instances=()

  if [[ -n "$INSTANCES" ]]; then
    IFS=',' read -r -a instances <<< "$INSTANCES"
    for i in "${!instances[@]}"; do
      instances[$i]="${instances[$i]// /}"
    done
  else
    mapfile -t instances < <(beam_list_worker_instances)
  fi

  if [[ "${#instances[@]}" -eq 0 ]]; then
    echo "No worker instances to enable. Add config/workers/<name>.env first." >&2
    return 1
  fi

  for instance in "${instances[@]}"; do
    [[ -z "$instance" ]] && continue
    if [[ ! -f "${ROOT}/config/workers/${instance}.env" ]]; then
      echo "Missing env file for instance ${instance}: ${ROOT}/config/workers/${instance}.env" >&2
      exit 1
    fi
  done

  beam_sync_workers
  for instance in "${instances[@]}"; do
    [[ -z "$instance" ]] && continue
    echo "  enabled beam-worker@${instance}.service -> config/workers/${instance}.env"
  done
}

if [[ ! -d "$SYSTEMD_DIR" ]]; then
  echo "Missing systemd templates: ${SYSTEMD_DIR}" >&2
  exit 1
fi

VENV="${ROOT}/venv"
if [[ ! -x "${VENV}/bin/python" ]]; then
  echo "Missing virtualenv: ${VENV}/bin/python" >&2
  echo "Create it first: python3 -m venv ${ROOT}/venv && pip install -e ." >&2
  exit 1
fi

mkdir -p "${ROOT}/logs/workers" "${ROOT}/run"

render_unit() {
  local src="$1"
  local dest_name="$2"
  sed \
    -e "s|@BEAM_ROOT@|${ROOT}|g" \
    -e "s|@BEAM_VENV@|${VENV}|g" \
    -e "s|@BEAM_USER@|${BEAM_USER}|g" \
    -e "s|@BEAM_GROUP@|${BEAM_GROUP}|g" \
    "$src" | sudo tee "${TARGET_DIR}/${dest_name}" >/dev/null
}

echo "Installing systemd units to ${TARGET_DIR}"
render_unit "${SYSTEMD_DIR}/beam-orchestrator.service" "beam-orchestrator.service"
render_unit "${SYSTEMD_DIR}/beam-worker-gateway.service" "beam-worker-gateway.service"
render_unit "${SYSTEMD_DIR}/beam-worker@.service" "beam-worker@.service"

sudo systemctl daemon-reload
echo "Installed:"
echo "  beam-orchestrator.service"
echo "  beam-worker-gateway.service"
echo "  beam-worker@.service"

if [[ "$ENABLE" -eq 1 ]]; then
  beam_systemctl enable beam-orchestrator.service
  beam_systemctl enable beam-worker-gateway.service
  echo "Enabled orchestrator and gateway. Start with:"
  echo "  ./scripts/run-orchestrator.sh"
  echo "  ./scripts/run-worker-gateway.sh"
  echo
  echo "Workers are separate. After creating config/workers/*.env:"
  echo "  ./scripts/install-systemd.sh --enable-workers"
  echo "  ./scripts/run-workers.sh start"
fi

if [[ "$ENABLE_WORKERS" -eq 1 ]]; then
  if ! beam_unit_installed "beam-worker@.service"; then
    echo "Worker template not installed. Run: $0 --enable" >&2
    exit 1
  fi
  enable_worker_instances
  echo "Enabled workers. Start with:"
  echo "  ./scripts/run-workers.sh start"
  echo
  echo "Add another worker later:"
  echo "  cp config/workers/worker1.env.example config/workers/worker3.env"
  echo "  ./scripts/install-systemd.sh --enable-workers"
  echo "  ./scripts/run-worker.sh worker3"
fi
